  const meta=()=>P.metadata.find(m=>m.id===state.patternId);
  const ranges={thickness:'thickness',patternScale:'scale',linePitch:'pitch',patternRotation:'rotation',endZone:'endZone',sideInset:'sideInset',lightAngle:'lightAngle',sheen:'sheen',imageZoom:'imageZoom',imageOffsetX:'imageOffsetX',imageOffsetY:'imageOffsetY',strokeRatio:'strokeRatio',amplitude:'amplitude',detail:'detail',jitter:'jitter',hatchAngle:'hatchAngle',stretchX:'stretchX',stretchY:'stretchY',offsetX:'offsetX',offsetY:'offsetY',secondaryRotation:'secondaryRotation',splitRatio:'splitRatio',overlayOpacity:'overlayOpacity'};
  const selects=['symmetry','renderStyle','compositionMode','secondaryPattern','imageFit'];
  function syncControls(){for(const[id,key]of Object.entries(ranges))$(id).value=state[key];for(const id of selects)$(id).value=state[id];$('seed').value=state.seed;$('showZones').checked=state.showZones;$('filamentColor').value=state.color;}
  function snapshot(){return {...state};}
  function comparable(s){const {image,...v}=s;return JSON.stringify({...v,image:image?.dataUrl||null});}
  function remember(){clearTimeout(historyTimer);historyTimer=setTimeout(()=>commit(),220);}
  function commit(){clearTimeout(historyTimer);const snap=snapshot();if(!history.length||comparable(history.at(-1))!==comparable(snap)){history.push(snap);if(history.length>70)history.shift();future.length=0;}historyUi();}
  function historyUi(){$('undo').disabled=history.length<2;$('redo').disabled=!future.length;}
  function restore(s){Object.assign(state,DEFAULT,s);syncControls();refresh();applyView(state.view);fit();historyUi();}
  function undo(){commit();if(history.length<2)return;future.push(history.pop());restore(history.at(-1));toast('Undone');}
  function redo(){clearTimeout(historyTimer);if(!future.length)return;const s=future.pop();history.push(s);restore(s);toast('Redone');}
  function refresh(){
    try{
    const p=panel();if(!p)throw Error('Unknown panel');state.sideInset=Math.min(state.sideInset,Math.floor((p.width-1)*2)/4);study=C.create(p,state);
    $('sideInset').max=String(Math.min(10,Math.floor((p.width-1)*2)/4));$('sideInset').value=state.sideInset;
    $('panelSize').value=p.id;$('stageEyebrow').textContent=p.label+' / '+p.format;$('stageTitle').textContent=name();$('patternRoute').textContent=C.routeNames[study.pattern.kind];
    $('panelDimensions').textContent=p.width.toFixed(2)+' × '+p.height.toFixed(2)+' × '+state.thickness.toFixed(1)+' mm';$('artDimensions').textContent='Artwork '+study.rectangle.width.toFixed(2)+' × '+study.rectangle.height.toFixed(2)+' mm';
    $('geometryNote').textContent=(p.hp===20?'UFO v2 outline':'zudo-blanks CAD')+' · '+p.holes.length+' mounting '+(p.holes[0].type==='circle'?'holes':'slots');
    const m=meta();$('selectedName').textContent=m.name;$('selectedFamily').textContent=m.family;$('patternDescription').textContent=state.image?'Imported artwork is fitted into the rectangle.':m.description+(study.pattern.paths.length===0?' No lines intersect this crop. Reduce motif size or shift position.':'');
    $('routeExplanation').textContent=C.routeNotes[study.pattern.kind];$('geometrySource').href=p.sourceUrl;
    $('geometryStats').textContent=study.pattern.paths.length.toLocaleString()+' paths · '+study.pattern.regions.length.toLocaleString()+' regions · '+(study.pattern.pointCount||0).toLocaleString()+' points';
    update3mfCapability();
    $('proceduralControls').hidden=!!state.image;$('imageControls').hidden=!state.image;if(state.image)$('imageName').textContent=state.image.name;
    for(const key of ['amplitude','detail','jitter'])$(key+'Row').hidden=!m.controls.includes(key);
    $('amplitudeLabel').textContent=({chevron:'Chevron slope',sunburst:'Center size','star-tiles':'Star inset','wave-field':'Wave amplitude','harmonic-waves':'Wave amplitude','sand-dunes':'Dune height','superellipse':'Shape','crosshatch':'Crossing angle','moire-lines':'Crossing angle','rayburst':'Center opening','phyllotaxis':'Dot size'})[state.patternId]||'Shape amplitude';
    $('detailLabel').textContent=({sunburst:'Sector count − 4',parquet:'Strip subdivisions','hilbert':'Curve detail','superellipse':'Round → square'})[state.patternId]||'Structure detail';
    $('seedRow').hidden=!m.random;$('grainRow').hidden=m.kind!=='regional';
    $('secondControls').hidden=state.compositionMode==='single';$('splitRow').hidden=state.compositionMode==='overlay';$('opacityRow').hidden=state.compositionMode!=='overlay';
    $('compositionNote').textContent=state.compositionMode==='overlay'?'Overlapping artwork only. A printable non-overlapping region partition is not exported.':'Both patterns are generated across the rectangle, then clipped at this split. Shape controls are shared.';
    const outputs={thicknessValue:state.thickness.toFixed(1)+' mm',scaleValue:state.scale.toFixed(2)+'×',pitchValue:state.pitch.toFixed(2)+' mm',rotationValue:state.rotation+'°',endValue:state.endZone.toFixed(2)+' mm',sideValue:state.sideInset.toFixed(2)+' mm',lightValue:state.lightAngle+'°',sheenValue:state.sheen+'%',imageZoomValue:state.imageZoom.toFixed(2)+'×',imageXValue:state.imageOffsetX+'%',imageYValue:state.imageOffsetY+'%',strokeValue:Math.round(state.strokeRatio*100)+'%',amplitudeValue:Math.round(state.amplitude*100)+'%',detailValue:String(state.detail),jitterValue:Math.round(state.jitter*100)+'%',hatchValue:state.hatchAngle+'°',stretchXValue:state.stretchX.toFixed(2)+'×',stretchYValue:state.stretchY.toFixed(2)+'×',offsetXValue:state.offsetX+'%',offsetYValue:state.offsetY+'%',secondRotationValue:state.secondaryRotation+'°',splitValue:Math.round(state.splitRatio*100)+'%',opacityValue:Math.round(state.overlayOpacity*100)+'%'};
    for(const[id,value]of Object.entries(outputs))$(id).textContent=value;
    document.querySelectorAll('[data-panel]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.panel===p.id)));document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===state.color)));document.querySelectorAll('[data-reference]').forEach(b=>b.setAttribute('aria-pressed',String(!!state.image&&b.dataset.reference===state.image.id)));
    $('favoritePattern').textContent=favorites.has(state.patternId)?'★ Favorited':'☆ Favorite';$('filamentColor').value=state.color;
    if(lastThumb!==state.patternId){drawPatternThumb($('selectedThumb'),m);lastThumb=state.patternId;}
    if(state.view==='flat')$('flatView').innerHTML=C.svg(study);updateModel();$('loading').hidden=true;
    }catch(error){console.error(error);toast('Could not render: '+error.message);$('loading').hidden=true;}
  }
  function choosePanel(id){state.panelId=id;refresh();fit();remember();}
  function choosePattern(id,keep=false){const m=P.metadata.find(m=>m.id===id);if(!m)return;commit();importSerial++;state.image=null;state.patternId=id;if(!keep)Object.assign(state,m.defaults);syncControls();refresh();commit();}
  function resetTransform(){Object.assign(state,{rotation:0,hatchAngle:0,stretchX:1,stretchY:1,offsetX:0,offsetY:0,symmetry:'none'});syncControls();refresh();remember();}
  function drawPatternThumb(canvas,m){
    const ctx=canvas.getContext('2d'),size=canvas.width;ctx.fillStyle='#2a3027';ctx.fillRect(0,0,size,size);
    const sample=P.generate(m.id,{width:48,height:48,pitch:m.kind==='regional'?.72:.9,scale:.75,seed:17,...m.defaults});
    const st={color:'#b69d70',sheen:80,lightAngle:35,renderStyle:'satin',compositionMode:'single'};ctx.save();ctx.scale(size/48,size/48);ctx.lineWidth=m.kind==='regional'?.55:.33;ctx.lineJoin='round';
    for(const b of C.bins(sample.paths,st)){ctx.strokeStyle=b.color;ctx.beginPath();for(const[a,c]of b.segments){ctx.moveTo(...a);ctx.lineTo(...c);}ctx.stroke();}ctx.restore();
  }
  function patternThumb(m){if(thumbnails.has(m.id))return thumbnails.get(m.id);const c=document.createElement('canvas');c.width=c.height=210;drawPatternThumb(c,m);const url=c.toDataURL();thumbnails.set(m.id,url);return url;}
  function filteredPatterns(){const q=$('patternSearch').value.trim().toLowerCase(),route=$('routeFilter').value;return P.metadata.filter(m=>(libraryFamily==='All patterns'||libraryFamily==='Featured'&&m.featured||libraryFamily==='Favorites'&&favorites.has(m.id)||m.family===libraryFamily)&&(route==='all'||m.kind===route)&&(!q||[m.name,m.family,m.description].join(' ').toLowerCase().includes(q)));}
  function renderFamilies(){const families=['Featured','All patterns','Favorites',...new Set(P.metadata.map(m=>m.family))];$('familyFilters').replaceChildren();for(const family of families){const b=document.createElement('button'),s=document.createElement('span');b.textContent=family;s.textContent=family==='Featured'?P.metadata.filter(m=>m.featured).length:family==='All patterns'?P.metadata.length:family==='Favorites'?favorites.size:P.metadata.filter(m=>m.family===family).length;b.append(s);b.setAttribute('aria-pressed',String(family===libraryFamily));b.addEventListener('click',()=>{libraryFamily=family;renderFamilies();renderLibrary();});$('familyFilters').append(b);}}
  function renderLibrary(){
    const serial=++librarySerial,list=filteredPatterns();$('resultCount').textContent=list.length+' patterns';$('noResults').hidden=!!list.length;const grid=$('libraryGrid');grid.replaceChildren();
    const nodes=list.map(m=>{const b=document.createElement('button');b.className='library-card';b.dataset.pattern=m.id;b.setAttribute('aria-pressed',String(state.patternId===m.id));b.setAttribute('aria-label',m.name+' — '+(m.kind==='regional'?'region-based design':m.kind==='custom'?'custom curves':'artwork'));const img=new Image();img.alt='';img.width=210;img.height=210;const title=document.createElement('strong');title.textContent=m.name;const label=document.createElement('span');label.className='route-small';label.textContent=m.kind==='regional'?'▧ Region-based':m.kind==='custom'?'∿ Custom curves':'◇ Artwork';b.append(img,title,label);if(favorites.has(m.id)){const star=document.createElement('span');star.className='favorite-dot';star.textContent='★';b.append(star);}b.addEventListener('click',()=>{choosePattern(m.id);$('libraryDialog').close();});grid.append(b);return{m,img};});
    let i=0;function batch(){if(serial!==librarySerial)return;const start=performance.now();while(i<nodes.length&&performance.now()-start<20){const {m,img}=nodes[i++];try{img.src=patternThumb(m);}catch(e){img.alt='Preview unavailable';}}if(i<nodes.length)requestAnimationFrame(batch);}requestAnimationFrame(batch);
  }
  function openLibrary(){renderFamilies();renderLibrary();$('libraryDialog').showModal();$('patternSearch').focus();}
  function favorite(){if(favorites.has(state.patternId))favorites.delete(state.patternId);else favorites.add(state.patternId);try{localStorage.setItem('zudo-surface-favorites-v2',JSON.stringify([...favorites]));}catch(e){toast('Favorite kept for this session; browser storage is unavailable.');}refresh();}
  function panelThumbnail(s){
    const p=D.presets.find(p=>p.id===s.panelId),ss={...s,pitch:Math.max(s.pitch,1),showZones:false},st=C.create(p,ss),c=document.createElement('canvas');c.height=350;c.width=Math.max(30,Math.round(350*p.width/p.height));const ctx=c.getContext('2d');
    // Clip the real outline before painting; then remove the original mounting holes.
    ctx.save();ctx.scale(c.width/p.width,c.height/p.height);ctx.beginPath();p.outer.forEach((q,i)=>ctx[i?'lineTo':'moveTo'](...q));ctx.closePath();ctx.clip();C.paint(ctx,st,c.width,c.height);ctx.restore();
    ctx.save();ctx.scale(c.width/p.width,c.height/p.height);ctx.globalCompositeOperation='destination-out';ctx.fillStyle='#000';for(const h of p.holes){ctx.beginPath();ctx.roundRect(h.x-h.width/2,h.y-h.height/2,h.width,h.height,h.radius);ctx.fill();}ctx.restore();return c.toDataURL();
  }
  const starters=[
    {title:'Copper pinwheel',patternId:'pinwheel',color:'#bd8551',scale:1,rotation:0},
    {title:'Quiet parquet',patternId:'parquet',color:'#b8a786',scale:1.45,detail:6,rotation:0},
    {title:'Hemp lattice',patternId:'hemp-leaf',color:'#b3a276',scale:.8,strokeRatio:.4},
    {title:'Sage topography',patternId:'topographic',color:'#92a397',scale:1.3,jitter:.6,detail:8,strokeRatio:.5},
    {title:'Brass dunes',patternId:'sand-dunes',color:'#caa852',scale:1,amplitude:.85,rotation:90},
    {title:'Silver fracture',patternId:'fractured-glass',color:'#b5bbc0',scale:1.25,jitter:.8,hatchAngle:30},
    {title:'Soft wave scales',patternId:'wave-scales',color:'#bfb99d',scale:1.1,detail:7,strokeRatio:.4},
    {title:'Midnight circuits',patternId:'circuit-tiles',color:'#47525e',scale:.85,renderStyle:'lines',strokeRatio:.45},
    {title:'Satin honeycomb',patternId:'hex-facets',color:'#c6aa77',scale:1,rotation:30},
    {title:'Tidal ribbons',patternId:'truchet-ribbons',color:'#7097a0',scale:1.3,detail:5,strokeRatio:.45},
    {title:'Agate symmetry',patternId:'agate',color:'#ae8069',scale:1,amplitude:.55,detail:9,symmetry:'quad'},
    {title:'Two grains',patternId:'basket-weave',color:'#b7a177',scale:1.1,compositionMode:'split-x',secondaryPattern:'chevron',secondaryRotation:0,splitRatio:.5}
  ];
  function openVariations(mode='variations'){
    variationMode=mode;const serial=++variationSerial,r=P.rng((Date.now()%2147483647)|0);variationStates=[];
    $('variationTitle').textContent=mode==='starters'?'A few good starting points.':'Twelve ways to '+meta().name.toLowerCase()+'.';$('variationEyebrow').textContent=mode==='starters'?'CURATED / EDITABLE RECIPES':'SAME PATTERN / NEW POSSIBILITIES';$('regenerateVariations').hidden=mode==='starters';$('variationGrid').replaceChildren();
    if(mode==='starters')variationStates=starters.map(patch=>({...DEFAULT,panelId:state.panelId,endZone:state.endZone,sideInset:state.sideInset,thickness:state.thickness,view:state.view,...P.metadata.find(m=>m.id===patch.patternId).defaults,...patch}));
    else for(let i=0;i<12;i++){const s={...state,image:null,seed:Math.floor(r()*1000000),scale:Math.round((.55+r()*1.4)*20)/20,rotation:[0,0,30,45,60,90][Math.floor(r()*6)],amplitude:Math.round((.15+r()*.75)*50)/50,detail:3+Math.floor(r()*9),jitter:Math.round(r()*50)/50,offsetX:Math.round((r()-.5)*24),offsetY:Math.round((r()-.5)*24),symmetry:['none','none','none','mirror-x','quad'][Math.floor(r()*5)]};variationStates.push(s);}
    if(!$('variationDialog').open)$('variationDialog').showModal();
    let i=0;function next(){if(serial!==variationSerial||i>=variationStates.length)return;const s=variationStates[i],index=i++,b=document.createElement('button');b.className='variation-card';const img=new Image();img.alt='';img.src=panelThumbnail(s);const title=document.createElement('h3');title.textContent=s.title||('Variation '+String(index+1).padStart(2,'0'));const note=document.createElement('p');note.textContent=mode==='starters'?P.metadata.find(m=>m.id===s.patternId).name:s.scale.toFixed(2)+'× · '+s.rotation+'° · '+(s.symmetry==='none'?'no mirror':s.symmetry)+' · seed '+s.seed;const num=document.createElement('span');num.className='sample-number';num.textContent=String(index+1).padStart(2,'0');b.append(num,img,title,note);b.addEventListener('click',()=>{commit();const {title,...settings}=s;Object.assign(state,settings);syncControls();refresh();commit();$('variationDialog').close();toast('Variation applied — all settings remain editable');});$('variationGrid').append(b);requestAnimationFrame(next);}requestAnimationFrame(next);
  }
  function persistSaved(){try{localStorage.setItem('zudo-surface-designs-v2',JSON.stringify(savedDesigns));return true;}catch(e){toast('Browser storage is full or unavailable. Use Save recipe for a portable copy.');return false;}}
  function saveDesign(){const title=(state.image?state.image.name:meta().name)+' · '+panel().label;const {image,...s}=snapshot();const entry={id:Date.now().toString(36),title,state:s,image:image?{dataUrl:image.dataUrl,name:image.name,width:image.width,height:image.height,id:image.id,sourceUrl:image.sourceUrl,credit:image.credit}:null,thumb:panelThumbnail(state)};savedDesigns.unshift(entry);savedDesigns=savedDesigns.slice(0,24);const stored=persistSaved();renderSaved();if(stored)toast('Design saved in this browser. Export a recipe for backup.');}
  function renderSaved(){$('savedShelf').hidden=!savedDesigns.length;$('savedDesigns').replaceChildren();for(const entry of savedDesigns){const wrap=document.createElement('div');wrap.style.position='relative';const b=document.createElement('button');b.className='saved-card';const img=new Image();img.src=entry.thumb;img.alt='';const span=document.createElement('span');span.textContent=entry.title;b.append(img,span);b.addEventListener('click',async()=>{commit();Object.assign(state,DEFAULT,entry.state,{image:null});if(entry.image){const image=new Image();image.src=entry.image.dataUrl;await image.decode();state.image={...entry.image,element:image};}syncControls();refresh();applyView(state.view);commit();});const del=document.createElement('button');del.className='delete-saved';del.textContent='✕';del.setAttribute('aria-label','Remove '+entry.title);del.addEventListener('click',()=>{savedDesigns=savedDesigns.filter(e=>e.id!==entry.id);persistSaved();renderSaved();});wrap.append(b,del);$('savedDesigns').append(wrap);}}
  function setupOptions(){
    for(const p of D.presets){const o=document.createElement('option');o.value=p.id;o.textContent=p.label+' — '+p.nominalWidth.toFixed(1)+' × '+p.nominalHeight.toFixed(1)+' mm';$('panelSize').append(o);}
    for(const hp of [4,8,12,16,20]){const p=D.presets.find(p=>p.hp===hp),b=document.createElement('button');b.textContent=p.label;b.dataset.panel=p.id;b.addEventListener('click',()=>choosePanel(p.id));$('sizeShortcuts').append(b);}
    for(const [label,color]of [['Copper','#bd8551'],['Graphite','#47525e'],['Silver','#b5bbc0'],['Gold','#caa852'],['Sage','#92a397'],['Blue','#447893']]){const b=document.createElement('button');b.className='swatch';b.style.background=color;b.dataset.color=color;b.title=label;b.setAttribute('aria-label',label+' filament');b.addEventListener('click',()=>{state.color=color;refresh();remember();});$('colorSwatches').append(b);}
    for(const ref of D.references){const b=document.createElement('button');b.className='reference-card';b.dataset.reference=ref.id;const img=new Image();img.src=ref.dataUrl;img.alt='';const label=document.createElement('span');label.textContent=ref.name;b.append(img,label);b.addEventListener('click',()=>loadImage(ref.dataUrl,ref.name,ref));$('referenceGrid').append(b);}
    for(const family of new Set(P.metadata.map(m=>m.family))){const group=document.createElement('optgroup');group.label=family;for(const m of P.metadata.filter(m=>m.family===family)){const opt=document.createElement('option');opt.value=m.id;opt.textContent=m.name;group.append(opt);}$('secondaryPattern').append(group);}
  }
  function normalizeRecipe(recipe){
    if(!recipe||!['zudo-surface-preview/v1','zudo-surface-preview/v2'].includes(recipe.schema))throw Error('Choose a Surface Lab v1 or v2 recipe, not a pgen JSON file.');
    let s={...DEFAULT};if(recipe.schema==='zudo-surface-preview/v2'){for(const k of Object.keys(DEFAULT))if(k!=='image'&&recipe.editorState?.[k]!==undefined)s[k]=recipe.editorState[k];}
    else {const par=recipe.artwork?.parameters||{},ar=recipe.artwork?.rectangle||{},a=recipe.appearance||{};Object.assign(s,{panelId:recipe.panel.id,patternId:recipe.artwork.patternId==='image'?'triangular-facets':recipe.artwork.patternId,thickness:recipe.panel.studyThickness,endZone:ar.y??12.25,sideInset:ar.x??0,pitch:par.pitch??.62,scale:par.scale??1,rotation:par.rotation??0,color:a.color||DEFAULT.color,lightAngle:a.lightAngle??35,sheen:a.sheen??65,showZones:a.showArtworkBoundary??true});}
    if(!D.presets.some(p=>p.id===s.panelId)||!P.metadata.some(m=>m.id===s.patternId))throw Error('This recipe uses an unavailable panel or pattern.');
    for(const[id,key]of Object.entries(ranges)){const element=$(id),n=Number(s[key]),min=Number(element.min),max=Number(element.max);if(!Number.isFinite(n)||n<min||n>max)throw Error('Recipe '+key+' is outside this editor’s range.');s[key]=n;}
    for(const id of selects)if(!Array.from($(id).options).some(o=>o.value===s[id]))throw Error('Invalid recipe '+id+'.');
    if(!/^#[0-9a-f]{6}$/i.test(s.color))throw Error('Invalid recipe color.');if(!Number.isInteger(s.seed)||s.seed<0||s.seed>2147483647)throw Error('Invalid recipe seed.');if(!['flat','angle'].includes(s.view))throw Error('Invalid view.');s.showZones=!!s.showZones;
    return s;
  }
  async function readRecipe(file){if(!file)return;try{if(file.size>35*1024*1024)throw Error('Recipe exceeds the 35 MB limit.');const recipe=JSON.parse(await file.text()),s=normalizeRecipe(recipe);if(recipe.reference){const ref=recipe.reference;if(typeof ref.dataUrl!=='string'||!/^data:image\/(png|jpe?g|webp|svg\+xml)[;,]/i.test(ref.dataUrl))throw Error('Recipe contains an unsupported image reference.');const img=new Image();img.src=ref.dataUrl;await img.decode();s.image={...ref,name:String(ref.name||'Imported image'),element:img,width:img.naturalWidth,height:img.naturalHeight};s.imageFit=ref.fit||s.imageFit;s.imageZoom=ref.zoom||s.imageZoom;s.imageOffsetX=ref.offsetXPercent||0;s.imageOffsetY=ref.offsetYPercent||0;}commit();Object.assign(state,s);syncControls();refresh();applyView(state.view);fit();commit();toast(recipe.schema.endsWith('/v1')?'v1 settings loaded. v2 algorithms may look different.':'Recipe restored with all design settings.');}catch(error){toast('Could not open recipe: '+error.message);}finally{$('recipeFile').value='';}}